package com.model;
// Generated 9 déc. 2015 19:54:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "GENRE")
public class Genre implements java.io.Serializable {

	private int idGenre;
	private Utilisateur utilisateur;
	private String nom;
	private int nbrChansons;
	private Date dateAjout;
	private Set<Ucg> ucgs = new HashSet<Ucg>(0);

	public Genre() {
	}

	public Genre(int idGenre, Utilisateur utilisateur, String nom, int nbrChansons, Date dateAjout) {
		this.idGenre = idGenre;
		this.utilisateur = utilisateur;
		this.nom = nom;
		this.nbrChansons = nbrChansons;
		this.dateAjout = dateAjout;
	}

	public Genre(int idGenre, Utilisateur utilisateur,  String nom, int nbrChansons, Date dateAjout,
			Set<Ucg> ucgs) {
		this.idGenre = idGenre;
		this.utilisateur = utilisateur;
		this.nom = nom;
		this.nbrChansons = nbrChansons;
		this.dateAjout = dateAjout;
		this.ucgs = ucgs;
	}

	@Id

	@Column(name = "ID_GENRE", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdGenre() {
		return this.idGenre;
	}

	public void setIdGenre(int idGenre) {
		this.idGenre = idGenre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USER", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "NOM", nullable = false, length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "NBR_CHANSONS", nullable = false, precision = 22, scale = 0)
	public int getNbrChansons() {
		return this.nbrChansons;
	}

	public void setNbrChansons(int nbrChansons) {
		this.nbrChansons = nbrChansons;
	}

	@Column(name = "DATE_AJOUT", nullable = false, length = 20)
	public Date getDateAjout() {
		return this.dateAjout;
	}

	public void setDateAjout(Date dateAjout) {
		this.dateAjout = dateAjout;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<Ucg> getUcgs() {
		return this.ucgs;
	}

	public void setUcgs(Set<Ucg> ucgs) {
		this.ucgs = ucgs;
	}
	public Date takeDate()
	{
			Date date = new Date();
			return date;
	}

}
