package com.model;
// Generated 9 déc. 2015 19:54:35 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ucg generated by hbm2java
 */
@Entity
@Table(name = "UCG")
public class Ucg implements java.io.Serializable {

	private int idUcg;
	private Utilisateur utilisateur;
	private Chanson chanson;
	private Genre genre;

	public Ucg() {
	}

	public Ucg(int idUcg, Utilisateur utilisateur, Chanson chanson, Genre genre) {
		this.idUcg = idUcg;
		this.utilisateur = utilisateur;
		this.chanson = chanson;
		this.genre = genre;
	}

	@Id

	@Column(name = "ID_UCG", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdUcg() {
		return this.idUcg;
	}

	public void setIdUcg(int idUcg) {
		this.idUcg = idUcg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USER", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CHANSON", nullable = false)
	public Chanson getChanson() {
		return this.chanson;
	}

	public void setChanson(Chanson chanson) {
		this.chanson = chanson;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GENRE", nullable = false)
	public Genre getGenre() {
		return this.genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

}
