package com.model;
// Generated 29 nov. 2015 17:39:53 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "UTILISATEUR")
public class Utilisateur implements java.io.Serializable {

	private int idUser;
	private String nom;
	private String prenom;
	private String email;
	private String pseudo;
	private String motDePasse;
	private Date dateAjout;
	private Set<Ucg> ucgs = new HashSet<Ucg>(0);
	private Set<Genre> genres = new HashSet<Genre>(0);

	public Utilisateur() {
	}

	public Utilisateur(int idUser, String nom, String prenom, String email, String pseudo, String motDePasse,
			Date dateAjout) {
		this.idUser = idUser;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.pseudo = pseudo;
		this.motDePasse = motDePasse;
		this.dateAjout = dateAjout;
	}

	public Utilisateur(int idUser, String nom, String prenom, String email, String pseudo, String motDePasse,
			Date dateAjout, Set<Genre> genres, Set<Ucg> ucgs) {
		this.idUser = idUser;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.pseudo = pseudo;
		this.motDePasse = motDePasse;
		this.dateAjout = dateAjout;
		this.genres = genres;
		this.ucgs = ucgs;
	}

	@Id

	@Column(name = "ID_USER", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "NOM", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "EMAIL", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PSEUDO", nullable = false, length = 30)
	public String getPseudo() {
		return this.pseudo;
	}

	public void setPseudo(String pseudo) {
		this.pseudo = pseudo;
	}

	@Column(name = "MOT_DE_PASSE", nullable = false, length = 30)
	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_AJOUT", nullable = false, length = 7)
	public Date getDateAjout() {
		return this.dateAjout;
	}

	public void setDateAjout(Date dateAjout) {
		this.dateAjout = dateAjout;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Ucg> getUcgs() {
		return this.ucgs;
	}


	public void setUcgs(Set<Ucg> ucgs) {
		this.ucgs = ucgs;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Genre> getGenres() {
		return this.genres;
	}

	public void setGenres(Set<Genre> genres) {
		this.genres = genres;
	}
	public Date takeDate()
	{
			Date date = new Date();
			return date;
	}

	@Override
	public String toString() {
		return "Utilisateur [idUser=" + idUser + ", nom=" + nom + ", prenom=" + prenom + ", email=" + email
				+ ", pseudo=" + pseudo + ", motDePasse=" + motDePasse + ", dateAjout=" + dateAjout + "]";
	}
	
}
